<?php

namespace Trackem\AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventRepository extends EntityRepository
{

    // Find event by ID
    public function findEvent($id) {

        return $this->getEntityManager()->createQuery(
            '
                SELECT 
                    event
                FROM 
                    AppBundle:Event event
                WHERE 
                    event.id = :id
            '
        )
            ->setParameter('id', $id)
            ->getResult();
    }



    // Find event given a the creator/user ID
    public function findEventWhereCreator($userId) {

        return $this->getEntityManager()->createQuery(
            '
                SELECT 
                    event
                FROM 
                    AppBundle:Event event
                WHERE 
                    event.createdBy = :userId
                ORDER BY 
                    event.createdDate
            '
        )
            ->setParameter('userId', $userId)
            ->getResult();
    }




}
