<?php

namespace Trackem\AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SessionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SessionRepository extends EntityRepository
{

    // Find session by ID
    public function findSession($id) {

        return $this->getEntityManager()->createQuery(
            '
                SELECT 
                    conference
                FROM 
                    "AppBundle:Session" session1
                WHERE 
                    session1.id = :id
            '
        )
            ->setParameter('id', $id)
            ->getResult();
    }


    // Find session by event ID
    public function findSessionByEvent($eventId) {

        return $this->getEntityManager()->createQuery(
            '
                SELECT 
                    session
                FROM 
                    AppBundle:Session session
                WHERE 
                    session.belongToEvent = :eventId
                ORDER BY
                    session.dateEnded
            '
        )
            ->setParameter('eventId', $eventId)
            ->getResult();
    }


}
